### ISSUE TITLE
Interfaz no se refresca luego de recibir configuraciones desde controlador

### ISSUE THREAD

**Issue by ddiaz-yx** [michaelvsj/respiface#4]
Ninguna de las configuraciones (current, default, min, max) está generando algún cambio en la interfaz. Sin entender mucho aún, para el caso de las configuraciones base _main.py:set_params_from_controller(...)_ solo parece estar guardando pero no aplicando nada. En el caso de las configuraciones actuales, _signal_new_param_value_ parece no estar conectado.

**Comment by michaelvsj** [comment]
Eso no lo he trabajado mucho. Es poco más que un esqueleto. Trataré de implementarlo ASAP
